name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: "Create env file"
        run: |
          touch .env
          echo DATABASE_URI= ${{ secrets.DATABASE_URI }} >> .env
          echo PAYLOAD_SECRET= ${{ secrets.PAYLOAD_SECRET }} >> .env
          echo CLOUDFLARE_ACCOUNT_ID= ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} >> .env
          echo CLOUDFLARE_ACCESS_KEY_ID= ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }} >> .env
          echo CLOUDFLARE_SECRET_ACCESS_KEY= ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }} >> .env
          echo CLOUDFLARE_BUCKET_NAME= ${{ secrets.CLOUDFLARE_BUCKET_NAME }} >> .env
          echo CLOUDFLARE_BUCKET_PUBLIC_LINK= ${{ secrets.CLOUDFLARE_BUCKET_PUBLIC_LINK }} >> .env
          echo CLOUDFLARE_REGION= ${{ secrets.CLOUDFLARE_REGION }} >> .env
          echo NEXT_PUBLIC_BUILD_DATE= ${{ secrets.NEXT_PUBLIC_BUILD_DATE }} >> .env
          echo MIXPANEL_TOKEN= ${{ secrets.MIXPANEL_TOKEN }} >> .env
          cat .env

      - name: Build the project
        run: pnpm run build
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}
          CLOUDFLARE_BUCKET_PUBLIC_LINK: ${{ secrets.CLOUDFLARE_BUCKET_PUBLIC_LINK }}
          CLOUDFLARE_REGION: ${{ secrets.CLOUDFLARE_REGION }}
          NEXT_PUBLIC_BUILD_DATE: ${{ secrets.NEXT_PUBLIC_BUILD_DATE }}
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./.next/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./.next/

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{secrets.DROPLET_PASSWORD}}
          source: "./.next/"
          target: "/var/www/portfolio-site/.next"

  reset-droplet:
    needs: deploy
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Restart your application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{secrets.DROPLET_PASSWORD}}
          script: |
            pm2 restart portfolio-site || pm2 start npm --name "portfolio-site" -- start
