name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies using pnpm
        run: npm install -g pnpm && pnpm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DATABASE_URI: ${{ secrets.DATABASE_URI }}
          envkey_PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          envkey_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          envkey_CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          envkey_CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          envkey_CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}
          envkey_CLOUDFLARE_BUCKET_PUBLIC_LINK: ${{ secrets.CLOUDFLARE_BUCKET_PUBLIC_LINK }}
          envkey_CLOUDFLARE_REGION: ${{ secrets.CLOUDFLARE_REGION }}
          envkey_NEXT_PUBLIC_BUILD_DATE: ${{ secrets.NEXT_PUBLIC_BUILD_DATE }}
          envkey_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}

      - name: Build the project
        run: pnpm run build

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          source: "./.next/"
          target: "/var/www/portfolio-site/.next"

      - name: Restart your application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          script: |
            pm2 restart portfolio-site || pm2 start npm --name "portfolio-site" -- start
